export const cardData = [
  { id: "1", title: "멘붕이에요", image: "🤯" },
  { id: "2", title: "슬퍼요", image: "🥲" },
  { id: "3", title: "화가나요", image: "🤬" },
  { id: "4", title: "기뻐요", image: "🤗" },
  { id: "5", title: "사랑해요", image: "🥰" },
  { id: "6", title: "기분좋아요", image: "😊" },
  { id: "7", title: "애원해요", image: "🥺" },
  { id: "8", title: "고민되요", image: "🤔" },
  { id: "9", title: "참아요", image: "😣" },
  { id: "10", title: "조용해요", image: "🤫" },
  { id: "11", title: "추워요", image: "🥶" },
  { id: "12", title: "축하해요", image: "🥳" },
  { id: "13", title: "놀랐어요", image: "😳" },
  { id: "14", title: "웃겨요", image: "🤣" },
  { id: "15", title: "슬퍼요", image: "😥" },
  { id: "16", title: "더워요", image: "🥵" },
  { id: "17", title: "우울해요", image: "😔" },
  { id: "18", title: "당황했어요", image: "😰" },
];
